name: quick-test

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENCE
      - CODEOWNERS

jobs:
  test-build:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Run Tests
        run: make test
